### PR TITLE
Add `@cond` command

### PR DESCRIPTION
**Pull request by nystrom**
Add a `@cond` command to register an expression at the current infiltration point. The next time that point is hit, infiltration will occur only if the expression evaluates to `true`. This is less efficient than the `@infiltrate cond` macro, but is more flexible in that the condition can be updated dynamically.

Example:
```
julia> function f(x)
         out = []
         for i in x
           push!(out, 2i)
           @infiltrate
         end
         out
       end
f (generic function with 1 method)

julia> f([1,2,3,4,5,6,7,8,9,10])
Infiltrating f(x::Vector{Int64})
  at REPL[10]:5

infil> @cond i > 5

infil> @continue
Conditionally enabled infiltration at this infiltration point.

Infiltrating f(x::Vector{Int64})
  at REPL[10]:5

infil> i
6
```

I'll add some tests if this seems worthwhile to eventually merge.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Thanks for this (and sorry for the delay in reviewing this)! I added a test for this, so no need to worry about that from your end :)

**Comment by nystrom** [comment]
Oh, thanks a lot for accepting the PR!

**Comment by pfitzseb** [comment]
Btw, I also added a note in the docs that this only takes local variables into account. Not sure how prohibitive the overhead of doing the eval at infiltration time would be, but that would solve the "issue".

**Comment by theogf** [comment]
That's a really cool feature! Thanks for adding it!

**Pull request merged**
